### ISSUE TITLE
Chain tests fails only on Windows

### ISSUE THREAD

**Issue by iNemesis21** [purpleprotocol/purple_prototype#48]
When running multiple times the tests, the ones from chain randomly fails.

```rust
failures:

---- chain::tests::append_stress_test stdout ----
thread 'chain::tests::append_stress_test' panicked at 'called `Result::unwrap()` on an `Err` value: AlreadyInChain', src\libcore\result.rs:997:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
thread 'chain::tests::append_stress_test' panicked at '[quickcheck] TEST FAILED (runtime error). Arguments: ()
Error: "called `Result::unwrap()` on an `Err` value: AlreadyInChain"', C:\Users\itodo\.cargo\registry\src\github.com-1ecc6299db9ec823\quickcheck-0.7.2\src\tester.rs:176:28

---- chain::tests::it_rewinds_correctly2 stdout ----
thread 'chain::tests::it_rewinds_correctly2' panicked at 'called `Result::unwrap()` on an `Err` value: AlreadyInChain', src\libcore\result.rs:997:5
thread 'chain::tests::it_rewinds_correctly2' panicked at '[quickcheck] TEST FAILED (runtime error). Arguments: ()
Error: "called `Result::unwrap()` on an `Err` value: AlreadyInChain"', C:\Users\itodo\.cargo\registry\src\github.com-1ecc6299db9ec823\quickcheck-0.7.2\src\tester.rs:176:28

---- chain::tests::stages_append_test4 stdout ----
thread 'chain::tests::stages_append_test4' panicked at 'assertion failed: `(left == right)`
  left: `BelongsToDisconnected`,
 right: `DisconnectedTip`', src\chain\src\chain.rs:4496:9

---- chain::tests::stages_append_test3 stdout ----
thread 'chain::tests::stages_append_test3' panicked at 'assertion failed: `(left == right)`
  left: `BelongsToDisconnected`,
 right: `DisconnectedTip`', src\chain\src\chain.rs:1988:9


failures:
    chain::tests::append_stress_test
    chain::tests::it_rewinds_correctly2
    chain::tests::stages_append_test3
    chain::tests::stages_append_test4

test result: FAILED. 6 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by octavonce** [comment]
I have added the project to the Windows CI pipeline and the tests seem to fail there as well:
<img width="973" alt="Screenshot 2019-05-15 at 11 36 46" src="https://user-images.githubusercontent.com/20557383/57765458-d0045f00-7705-11e9-943e-743b1464aa21.png">

This is pretty weird since all of the tests seem to pass on osx and linux. Even the stress test passes which always generates random inputs for tests. What makes this even more weird is that there are no build errors but runtime errors which would normally reflect unsound or brittle logic, however the logic seems to be sound on unix systems? 

I don't know what the cause might be. It seems that something on Windows specifically causes the code to be non-deterministic. Maybe one of the packages has something to do about this? 

My first guess would be the rocksdb package since it wasn't exactly designed to run on windows and the tested module relies on disk writes and accesses for the intended behavior. However this is weird since we are using the rocksdb-sys crate that is exported by parity whom do windows builds themselves.

This definitely requires a thorough investigation.
